#!/bin/sh
#
# @name Kart
#

. ${R}etc/init.d/rc.rover_defaults

param set-default GND_L1_DIST 2
param set-default GND_L1_PERIOD 7
param set-default GND_SP_CTRL_MODE 1
param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_I 3
param set-default GND_SPEED_IMAX 0.125
param set-default GND_SPEED_P 0.25
param set-default GND_SPEED_THR_SC 1
param set-default GND_SPEED_TRIM 4
param set-default GND_THR_CRUISE 0.3
param set-default GND_THR_MAX 0.5
param set-default GND_THR_MIN 0

param set-default NAV_ACC_RAD 0.5
param set-default NAV_LOITER_RAD 2

param set-default GND_MAX_ANG 0.785
param set-default GND_WHEEL_BASE 0.776

param set-default CA_AIRFRAME 5

param set-default CA_R_REV 1
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC6 101
param set-default PWM_MAIN_FUNC7 101

param set-default EKF2_EN 1

param set-default CP_DIST -1

