#!/bin/sh
#
# @name Kart
#

. ${R}etc/init.d/rc.rover_defaults

param set-default GND_L1_DIST 3
param set-default GND_L1_PERIOD 6

param set-default GND_SP_CTRL_MODE 1
param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_I 0.01
param set-default GND_SPEED_IMAX 0.2
param set-default GND_SPEED_P 0.25
#param set-default GND_SPEED_THR_SC 1
param set-default GND_SPEED_THR_SC 5
param set-default GND_SPEED_TRIM 4
#param set-default GND_THR_CRUISE 0.3
param set-default GND_THR_CRUISE 0.5
param set-default GND_THR_MAX 0.5
param set-default GND_THR_MIN 0

param set-default NAV_ACC_RAD 0.5
param set-default NAV_LOITER_RAD 2

#param set-default GND_MAX_ANG 0.785
param set-default GND_MAX_ANG 0.648
param set-default GND_WHEEL_BASE 0.776

param set-default CA_AIRFRAME 5

param set-default CA_R_REV 1
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC6 101
param set-default PWM_MAIN_FUNC7 101

param set-default EKF2_EN 1

param set-default CP_DIST -1

#----------------------------------------

# param set-default AHRS_EKF_TYPE 2
# param set-default AHRS_GPS_USE 1
# param set-default AHRS_ORIENTATION 0
# param set-default ARMING_REQUIRE 0
# param set-default BTN_ENABLE 0
# param set-default COMPASS_EXTERN2 0
# param set-default COMPASS_EXTERN3 0
# param set-default COMPASS_EXTERNAL 1
# param set-default COMPASS_ORIENT 8
# param set-default COMPASS_ORIENT2 0
# param set-default COMPASS_ORIENT3 0
# param set-default COMPASS_PRIMARY 0
# param set-default COMPASS_TYPEMASK 0
# param set-default COMPASS_USE 0
# param set-default COMPASE_USE2 1
# param set-default COMPASS_USE3 0
# param set-default CRUISE_SPEED 2

# param set-default WP_OVERSHOOT 2
# param set-default WP_RADIUS 2
# param set-default WP_SPEED 0

#---------------------------------

# ##param set BAT_N_CELLS 2

# param set EKF2_ANGERR_INIT 0.01
# param set EKF2_GBIAS_INIT 0.01
# param set EKF2_MAG_TYPE 1

# param set FW_AIRSPD_MAX 3
# param set FW_AIRSPD_MIN 0
# param set FW_AIRSPD_TRIM 1

# param set GND_L1_DIST 10
# param set GND_SP_CTRL_MODE 1
# param set GND_SPEED_P 0.25
# #param set GND_SPEED_I 0.001
# param set GND_SPEED_I 1
# param set GND_SPEED_D 3
# param set GND_SPEED_IMAX 0.125
# param set GND_SPEED_THR_SC 1
# ##param set GND_THR_IDLE 0
# param set GND_THR_CRUISE 0
# param set GND_THR_MAX 0.5
# param set GND_THR_MIN 0
# ##param set GND_WR_P 2
# ##param set GND_WR_I 0.9674
# ##param set GND_WR_IMAX 0.1
# ##param set GND_WR_D 1.2

# # param set MIS_LTRMIN_ALT 0.01
# # param set MIS_TAKEOFF_ALT 0.01

# # param set NAV_ACC_RAD 0.5

# # Provide ESC a constant 1500 us pulse
# # param set PWM_DISARMED 1500
# # param set PWM_MAX 2000
# # param set PWM_MIN 1000
